### ISSUE TITLE
RSS description content (yoy.be)

### ISSUE THREAD

**Issue by EricGrange** [stijnsanders/tx#1]
Might be a bit off-topic issue, but I was asked to add http://yoy.be/ to https://www.beginend.net/, however the description field of your RSS feed includes non-description info like the header, which thus messes up the summary text (cf. https://www.beginend.net/?feed=185)

For instance one description in the RSS is the following CDATA

```
<p><b>SHA-512</b><br />
<span style="font-size=xx-small;">2015-06-23 21:25
&nbsp;sha512
&nbsp;<a href="http://yoy.be/coding.html"><img src="http://yoy.be/cat/cat_coding.gif" class="c" alt="coding" width="50" height="13" /></a>&nbsp;<a href="http://yoy.be/delphi.html"><img src="http://yoy.be/cat/cat_delphi.gif" class="c" alt="delphi" width="50" height="13" /></a>&nbsp;<a href="http://yoy.be/freeware.html"><img src="http://yoy.be/cat/cat_freeware.gif" class="c" alt="freeware" width="50" height="13" /></a>
&nbsp;<a href="http://yoy.be/SHA-512.html">[permalink]</a></span></p>
<p><strong>&rarr;&nbsp;<a href="md5.html">md5</a></strong></p>
<p>I added SHA-512 to the collection! I also had a quick comparison with&nbsp;code similar to some other implementations where instead of a loop, a long list of 'round' calls are made, with some convolution made in the arguments, and it turns out the way I go at it here performs better. (Your milage may vary)<br clear="all" /></p>
```

As you can see the actual description is just a p tag at the very end, the rest of the info (like the date or title) should be in other nodes.

**Comment by stijnsanders** [comment]
It's nice to see it's you behind this website (seems logic now it's based on dwScript!)
Yes I proposed to add my feed, I'm glad you tracked me down here.
Could you force-refresh the feed? I've modified the <description> tags, they indeed used too much of the page-HTML script, and now only hold the post body.

**Comment by stijnsanders** [comment]
looks much better, thank you.
